- name: install pip
  apt:
    name: python3-pip
    state: latest
  become: true

- name: Install setuptools-scm
  pip:
    name: setuptools-scm
  become: true

    
- name: pip install docker-py
  pip:
    name:
      - docker
      - docker-compose

- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports: 8080:8080
    state: started
 
